language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - pypy
    - pypy3

install:
 - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib unittest2; fi
 - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install --install-option='--no-cython-compile' cython ; fi

script:
 - python setup.py build_ext --inplace
 - nosetests -vv

notifications:
    email:
        on_success: change
        on_failure: change

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
